# Project Euler Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

first, i = 0, 0
second = 1
sequence = []

while i <= 4000000
  i = first + second
  sequence << i if i % 2 == 0
  first = second
  second = i
end
puts "The sum of the even valued terms is #{sequence.inject(:+)}"